<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cine [
   <!ELEMENT cine (directores, peliculas)>
   <!ELEMENT directores (director)*>
      <!ELEMENT director (#PCDATA)>
         <!ATTLIST director coddir ID #REQUIRED>
   <!ELEMENT peliculas (pelicula)*>
      <!ELEMENT pelicula (#PCDATA)>
         <!ATTLIST pelicula direccion IDREF #REQUIRED>
]>
<!-- para la película Titanic se ha indicado en su atributo direccion el valor "JC", que es el valor del atributo coddir del director James Cameron.
En este documento XML, el atributo de tipo IDREF se ha definido obligatorio, #REQUIRED. Pero, a un atributo IDREF también se le puede especificar un valor por defecto, un valor fijo o que sea opcional escribirlo, #IMPLIED. -->
<cine>
   <directores>
      <director coddir="CE">Clint Eastwood</director>
      <director coddir="JC">James Cameron</director>
   </directores>
   <peliculas>
      <pelicula direccion="JC">Avatar</pelicula>
      <pelicula direccion="CE">Mystic River</pelicula>
      <pelicula direccion="JC">Titanic</pelicula>
   </peliculas>
</cine>